<?php
/**
 * Created by PhpStorm.
 * User: samson
 * Date: 3/11/2018
 * Time: 7:21 PM
 */

namespace App\Repositories\Admin;

use App\Models\Admin;
use App\Repositories\BaseRepository;
use App\Repositories\DefaultRepository;
use Illuminate\Container\Container as Application;

class AdminAccountsRepository extends BaseRepository
{

    use DefaultRepository;

    protected $routeIndex;
    protected $routeEdit;
    protected $routeCreate;
    protected $routeDestroy;

    public function __construct(Application $app)
    {
        parent::__construct($app);
        $this->routeIndex = 'admin.admin_accounts.index';
        $this->routeCreate = 'admin.admin_accounts.create';
        /*$this->routeEdit = 'admin.categories.edit';*/
        $this->routeDestroy = 'admin.admin_accounts.destroy';
    }

    /**
     * Specify Model class name
     *
     * @return string
     */
    function model()
    {
        return Admin::class;
    }

    public function create(array $attributes)
    {
        $attributes[Admin::COLUMN_PASSWORD] = bcrypt($attributes[Admin::COLUMN_PASSWORD]);
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return bool
     */
    public function deleteAdminAccount($id){
        $adminAccount = $this->findWithoutFail($id);

        if (empty($adminAccount)){
            return false;
        }
        $adminAccount->delete();
        return true;
    }
}